# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='zip_code',
            new_name='zip',
        ),
    ]
